---
# .kubernetes/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-production

resources:
  - ../../base

patchesStrategicMerge:
  - keycloak-prod-config.yaml

commonLabels:
  environment: production
