---
# Self-signed certificate for CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: cert-manager
spec:
  secretName: ca-key-pair
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  commonName: "Kind Development CA"
  isCA: true
  privateKey:
    algorithm: RSA
    size: 2048
  subject:
    organizationalUnits:
      - "Development"
    organizations:
      - "Kind Cluster"
    countries:
      - "US"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
# Certificate for Keycloak
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  secretName: keycloak-tls-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: keycloak.local
  dnsNames:
    - keycloak.local
    - keycloak.kind.local
    - localhost
  ipAddresses:
    - 127.0.0.1
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
---
# Certificate for Keycloak
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: keycloak.local
  dnsNames:
    - keycloak.local
    - keycloak.kind.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
