# .kubernetes/base/cert-manager/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cert-manager-base

resources:
  - certificate.yaml
  - cluster-issuer.yaml
  - namespace.yaml
  - release.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: cert-manager
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/part-of: cert-manager
