apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - ingressclass.yaml
  - job.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - rolecluster.yaml
  - service.yaml
  - serviceaccount.yaml
  - validatingwebhookconfiguration.yaml
