---
# .kubernetes/code/keycloak-admin-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
type: Opaque
data:
  credentials: eyJ1cmwiOiJodHRwOi8va2V5Y2xvYWstcmVsZWFzZS5rZXljbG9hay5zdmMuY2x1c3Rlci5sb2NhbDo4MDgwIiwiY2xpZW50X2lkIjoiYWRtaW4tY2xpIiwiZ3JhbnRfdHlwZSI6InBhc3N3b3JkIiwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW4ifQ==
