---
# .kubernetes/overlays/development/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-development

resources:
  - ../../base

patchesStrategicMerge:
  - keycloak-dev-config.yaml

commonLabels:
  environment: development
